// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyLopHoc.Models;

#nullable disable

namespace QuanLyLopHoc.Migrations
{
    [DbContext(typeof(SMContext))]
    [Migration("20230404124109_db01")]
    partial class db01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.DetailRollCall", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RollCallId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RollCallTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId", "RollCallId");

                    b.HasIndex("RollCallId");

                    b.ToTable("DetailRollCall");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.DetailTranscript", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TranscriptId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DiemCC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiemCK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiemTB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiemTX")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserId", "TranscriptId");

                    b.HasIndex("TranscriptId");

                    b.ToTable("DetailTranscript");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NTEXT");

                    b.Property<string>("ReceiverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NTEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PostTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Reply", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentRepId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("StudentRepId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.RollCall", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SubjectId");

                    b.ToTable("RollCall");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.StudentSubject", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubject");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NTEXT");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.TeacherSubject", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("TeacherSubject");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.TeacherTranscript", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TranscriptId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "TranscriptId");

                    b.HasIndex("TranscriptId");

                    b.ToTable("TeacherTranscript");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Transcript", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Transcript");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("NCHAR(255)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("Char(12)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.DetailRollCall", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.RollCall", "RollCall")
                        .WithMany("Details")
                        .HasForeignKey("RollCallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "Student")
                        .WithMany("Rollcalls")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RollCall");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.DetailTranscript", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.Transcript", "Transcript")
                        .WithMany("Details")
                        .HasForeignKey("TranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "Student")
                        .WithMany("Details")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Transcript");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Message", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "Receiver")
                        .WithMany("Received")
                        .HasForeignKey("ReceiverId")
                        .IsRequired();

                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "Sender")
                        .WithMany("Sent")
                        .HasForeignKey("SenderId")
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Notification", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Post", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyLopHoc.Models.Entities.Subject", "Subject")
                        .WithMany("Posts")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Reply", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.Post", "OriginPost")
                        .WithMany("Replies")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "StudentRep")
                        .WithMany("Replies")
                        .HasForeignKey("StudentRepId");

                    b.Navigation("OriginPost");

                    b.Navigation("StudentRep");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.RollCall", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyLopHoc.Models.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.StudentSubject", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "Users")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Subject", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "Creator")
                        .WithMany("CreatedSubject")
                        .HasForeignKey("CreatorId")
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.TeacherSubject", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "User")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.TeacherTranscript", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.Transcript", "Transcript")
                        .WithMany("TeacherTranscripts")
                        .HasForeignKey("TranscriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "User")
                        .WithMany("TeacherTranscripts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transcript");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Transcript", b =>
                {
                    b.HasOne("QuanLyLopHoc.Models.Entities.User", "Creator")
                        .WithMany("CreatedTranscript")
                        .HasForeignKey("CreatorId")
                        .IsRequired();

                    b.HasOne("QuanLyLopHoc.Models.Entities.Subject", "Subject")
                        .WithMany("Transcripts")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Post", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.RollCall", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Subject", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("StudentSubjects");

                    b.Navigation("TeacherSubjects");

                    b.Navigation("Transcripts");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.Transcript", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("TeacherTranscripts");
                });

            modelBuilder.Entity("QuanLyLopHoc.Models.Entities.User", b =>
                {
                    b.Navigation("CreatedSubject");

                    b.Navigation("CreatedTranscript");

                    b.Navigation("Details");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("Received");

                    b.Navigation("Replies");

                    b.Navigation("Rollcalls");

                    b.Navigation("Sent");

                    b.Navigation("StudentSubjects");

                    b.Navigation("TeacherSubjects");

                    b.Navigation("TeacherTranscripts");
                });
#pragma warning restore 612, 618
        }
    }
}
